package jboss.cloud.balancer


import org.drools.solver.core.score.calculator.HardAndSoftConstraintScoreCalculator;
import org.drools.solver.core.score.constraint.IntConstraintOccurrence;
import org.drools.solver.core.score.constraint.ConstraintType
import java.util.ArrayList

import jboss.cloud.balancer.AppServerInstance

global HardAndSoftConstraintScoreCalculator scoreCalculator

// ############################################################################
// Hard constraints
// ############################################################################

rule "tooManyApps"
    when
        app : AppServerInstance(apps.size > 5)
    then
        insertLogical(new IntConstraintOccurrence("too many apps", ConstraintType.NEGATIVE_HARD, app.getApps().size(), app));
end


rule "favourFewerAppServers"
    when
        AppServerInstance(apps.size == 0)
    then
        //score one up for a free app server
        insertLogical(new IntConstraintOccurrence("free server", ConstraintType.POSITIVE, 10));        
end

rule "punishNonFree"
    when
        not AppServerInstance(apps.size == 0)
    then
        insertLogical(new IntConstraintOccurrence("none free", ConstraintType.POSITIVE, -10));
end

        





// ############################################################################
// Calculate score
// ############################################################################

// Accumulate hard constraints
rule "hardConstraintsBroken"
        salience -1 // Do the other rules first (optional, for performance)
    when
        $hardTotal : Number() from accumulate(
            IntConstraintOccurrence(constraintType == ConstraintType.NEGATIVE_HARD, $weight : weight),
            sum($weight) // Vote for http://jira.jboss.com/jira/browse/JBRULES-1075
        );
    then
        scoreCalculator.setHardConstraintsBroken($hardTotal.intValue());
end

// Accumulate soft constraints
rule "softConstraintsBroken"
        salience -1 // Do the other rules first (optional, for performance)
    when
        $softTotal : Number() from accumulate(
            IntConstraintOccurrence(constraintType == ConstraintType.POSITIVE, $weight : weight),
            sum($weight) // Vote for http://jira.jboss.com/jira/browse/JBRULES-1075
        );
    then
        scoreCalculator.setSoftConstraintsBroken(-$softTotal.intValue());
end

