package jboss.cloud.elastic


#Can have Metric generic object - many of them?
#or a map on AppServer?
rule "All loaded up"
    when
        cluster: Cluster()
        forall(Metric(cluster == c, name="cpu", value > 0.7))
    then
        requestNewApplicationServer("to busy CPU")
end



rule "Empty server"
    when
        srv: ServerInstance()
        not ClusterNode(server == srv)
    then
        shutdown(srv)
end


#more strongly typed??
rule "Can scale down"
    when
       srv: Server()
       as: AppServerInstance(sessionCount < 2, server == srv)
       exists AppServerInstance(sessionCount < 5, server != srv)
    then
       shutdownApplicationServer(as)
end


#and so on...

#what about CEP to have a stream of events - looking for a trend? can be as fast as we like... can use time windows? 
