package jboss.cloud.elastic

rule "All loaded up"
    when
        not AppServerInstance(busyConnectors < 20)
    then
        requestNewApplicationServer("Connection busy")
end

rule "Empty server"
    when
        srv: Server()
        not AppServerInstance(server == srv)
    then
        shutdown(srv)
end


rule "Can scale down"
    when
       srv: Server()
       as: AppServerInstance(sessionCount < 2, server == srv)
       exists AppServerInstance(sessionCount < 5, server != srv)
    then
       shutdownApplicationServer(as)
end


#and so on...
